import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was auto-generated by the CLI
import 'screens/onboarding_screen.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/register_screen.dart';

void main() async {
  // Required for async initialization
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const GameAndGrooveApp());
}

class GameAndGrooveApp extends StatelessWidget {
  const GameAndGrooveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Game & Groove',
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(
          0xFF0F0F13,
        ), // Deep dark background
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF00E5FF), // Neon Cyan accent
          secondary: Color(0xFFFF0055), // Neon Pink/Red accent
          surface: Color(0xFF1C1C23), // Slightly lighter dark for cards
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF0F0F13),
          elevation: 0,
          centerTitle: true,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
            letterSpacing: 1.5,
          ),
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Color(0xFF1C1C23),
          selectedItemColor: Color(0xFF00E5FF),
          unselectedItemColor: Colors.grey,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF00E5FF),
            foregroundColor: Colors.black,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          ),
        ),
        useMaterial3: true,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const OnboardingScreen(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(), // Add this line
        '/home': (context) => const MainNavigation(),
      },
      debugShowCheckedModeBanner: false,
    );
  }
}
